/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package angel.number.calculator;

public class App {
    public static void main(String[] args) {
        new Util().Exit("failure", "Text 123");
    }
}
